FROM node:22.14.0-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY . /app

ARG STORYBLOK_PAT_TOKEN
ENV STORYBLOK_PAT_TOKEN=$STORYBLOK_PAT_TOKEN

ARG NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN
ENV NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN=$NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN

ARG STORYBLOK_SPACE_ID
ENV STORYBLOK_SPACE_ID=$STORYBLOK_SPACE_ID

RUN rm -rf /app/.git
RUN rm -rf /app/.husky

RUN export NODE_ENV=production

RUN pnpm i
RUN pnpm run build

EXPOSE 3000

CMD pnpm run start
